var data = [
    {
        content: 'Ingrid & Conrad',
        type: 'Podcast',
        start: '2015-06-06',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: 'Fria Tider',
        type: 'News',
        start: '2009-01-01',
        end: stillGoingStrong,
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Avpixlat',
        type: 'News',
        start: '2011-01-01',
        end: '2017-08-30',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'exponerat.net',
        type: 'News',
        start: '2009-01-01',
        end: '2016-08-01',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Herr Nationell',
        type: 'Podcast',
        start: '2009-05-01',
        end: '2012-06-10',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Radio Länsman',
        type: 'Podcast',
        start: '2012-06-10',
        end: '2015-09-10',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Radio Realism',
        type: 'Podcast',
        start: '2015-09-10',
        end: '2017-09-08',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Verklighetschecken',
        type: 'Podcast',
        start: '2017-09-10',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: 'Radio Framåt',
        type: 'Podcast, News, TV',
        start: '2012-08-14',
        end: '2014-02-03',
        dateAccuracy: 'Estimated',
    },
    {
        content: ' Motgift ',
        type: 'Podcast, News, TV',
        start: '2014-02-05',
        end: stillGoingStrong,
        dateAccuracy: 'Estimated',
    },
    {
        content: ' MUF ',
        type: 'Podcast',
        start: '2015-06-01',
        end: '2016-06-06',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Vita Pillret',
        type: 'Podcast',
        start: '2017-08-22',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: 'RN DIREKT',
        type: 'Podcast',
        start: '2016-10-06',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: 'Radio Regeringen',
        type: 'Podcast',
        start: '2016-08-29',
        end: stillGoingStrong,
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Den Kokta Grodan',
        type: 'Podcast',
        start: '2016-01-14',
        end: stillGoingStrong,
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Studio Nordfront',
        type: 'TV',
        start: '2017-11-16',
        end: stillGoingStrong,
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Granskning Sverige',
        type: 'Podcast & TV',
        start: '2014-03-06',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: 'Dispatch International',
        type: 'News',
        start: '2012-01-30',
        end: '2016-03-01',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Den Här Dan',
        type: 'TV',
        start: '2018-01-11',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: 'Godmorgon Med Magnus',
        type: 'Podcast',
        start: '2016-08-22',
        end: '2018-03-16',
        dateAccuracy: 'Verified',
    },
    {
        content: 'Passningen',
        type: 'Podcast (sport)',
        start: '2015-09-01',
        end: stillGoingStrong,
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Kafferepet',
        type: 'Podcast',
        start: '2016-03-22',
        end: '2017-12-08',
        dateAccuracy: 'Verified',
    },
    {
        content: 'Spelnationen',
        type: 'Podcast',
        start: '2016-09-12',
        end: '2017-04-26',
        dateAccuracy: 'Verified',
    },
    {
        content: 'Blågula Frågor',
        type: 'Podcast & News',
        start: '1995-01-01',
        end: '2016-11-24',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Tidningen Svegot',
        type: 'Podcast & News',
        start: '2018-02-22',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: ' info14 ',
        type: 'News',
        start: '1995-04-01',
        end: '2011-03-01',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Den Svenske',
        type: 'News',
        start: '1933-01-25',
        end: '1950-01-01',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Den Sanne Nationalsocialisten',
        type: 'News',
        start: '2001-01-01',
        end: '2008-01-01',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Nordfront',
        type: 'News',
        start: '2009-01-01',
        end: stillGoingStrong,
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Nationellt Motstånd',
        type: 'News',
        start: '2003-01-01',
        end: '2010-02-28',
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Nordisk.nu',
        type: 'Portal',
        start: '2007-04-18',
        end: '2017-04-26',
        dateAccuracy: 'Verified',
    },
    {
        content: 'Me ne frego',
        type: 'Podcast',
        start: '2017-10-16',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: ' Motpol',
        type: 'News',
        start: '2015-03-23',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: 'Nya Tider',
        type: 'News',
        start: '2012-11-01',
        end: stillGoingStrong,
        dateAccuracy: 'Estimated',
    },
    {
        content: 'Palaestra Media',
        type: 'TV',
        start: '2017-10-12',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
    {
        content: 'Kväll med Svegot',
        type: 'Radio/Podcast',
        start: '2018-04-03',
        end: stillGoingStrong,
        dateAccuracy: 'Verified',
    },
];

